-- begin DEBTINFO_SESSION
alter table DEBTINFO_SESSION add constraint FK_DEBTINFO_SESSION_ON_DEBTOR foreign key (DEBTOR_ID) references DEBTINFO_DEBTOR(ID)^
alter table DEBTINFO_SESSION add constraint FK_DEBTINFO_SESSION_ON_LETTER foreign key (LETTER_ID) references DEBTINFO_LETTER(ID)^
create index IDX_DEBTINFO_SESSION_ON_DEBTOR on DEBTINFO_SESSION (DEBTOR_ID)^
create index IDX_DEBTINFO_SESSION_ON_LETTER on DEBTINFO_SESSION (LETTER_ID)^
-- end DEBTINFO_SESSION
